name: Flutter CI

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar o Flutter
      uses: subosito/flutter-action@v5
      with:
        flutter-version: '3.13.6'  # Substitua pela versão do Flutter que você deseja usar

    - name: Instalar dependências
      run: flutter pub get

    - name: Executar testes
      run: flutter test

    # Adicione etapas adicionais conforme necessário, como construir um APK ou realizar implantações.
